project:
  type: website
  output-dir: docs
  resources:
    - files/**
  render:
    - "index.*.qmd"

website:
  site-url: https://vanessa-kenniche-sanocka.github.io/
  navbar:
    pinned: true
    title: "<strong>VANESSA KENNICHE SANOCKA</strong>"
    left:
      - text: "About"
        href: "#about"
      - text: "Professional"
        menu:
          - text: "ML & Data Engineering"
            href: "#experience-ml"
          - text: "Data Science"
            href: "#experience-ds"
      - text: "Academic"
        href: "#education"
      - text: "Other"
        href: "#other"
      - text: "Overview"
        href: "#overview"
    right:
      - text: "<img src='images/us.svg' alt='US' class='flag-icon'> EN"
        href: index.en.html
      - text: "<img src='images/fr.svg' alt='FR' class='flag-icon'> FR"
        href: index.fr.html
      - text: "<img src='images/pl.svg' alt='PL' class='flag-icon'> PL"
        href: index.pl.html
format:
  html:
    link-external-newwindow: true
    theme: cosmo
    css: styles.css
    smooth-scroll: true
    page-layout: full
    title-block-style: none
    include-in-header:
      - theme-init.html
      - fonts.html
    include-after-body:
      - scripts.html  